apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: k8sgpt
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'teams-webhook'
      routes:
      - match:
          component: k8sgpt
          severity: critical
        receiver: 'teams-webhook'
    receivers:
    - name: 'teams-webhook'
      webhook_configs:
      - url: 'YOUR_TEAMS_WEBHOOK_URL'
        send_resolved: true
