apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8sgpt-alerts
  namespace: k8sgpt
spec:
  groups:
    - name: k8sgpt.rules
      interval: 30s
      rules:
        - alert: K8sGPTCriticalIssues
          expr: sum(k8sgpt_issues_by_severity{severity="critical"}) > 0
          for: 5m
          labels:
            severity: critical
            component: k8sgpt
          annotations:
            summary: "Issues critiques détectées par K8sGPT"
            description: "{{ $value }} issues critiques détectées nécessitant une action immédiate"

        - alert: K8sGPTTooManyIssues
          expr: sum(k8sgpt_issues_total) > 20
          for: 10m
          labels:
            severity: warning
            component: k8sgpt
          annotations:
            summary: "Trop d'issues détectées dans le cluster"
            description: "{{ $value }} issues totales détectées, investigation nécessaire"

        - alert: K8sGPTNoRemediation
          expr: (sum(k8sgpt_issues_total) - sum(k8sgpt_remediation_available)) > 10
          for: 15m
          labels:
            severity: warning
            component: k8sgpt
          annotations:
            summary: "Beaucoup d'issues sans remédiation automatique"
            description: "{{ $value }} issues sans solution de remédiation disponible"

        - alert: K8sGPTAnalysisFailure
          expr: rate(k8sgpt_analysis_errors_total[5m]) > 0.1
          for: 5m
          labels:
            severity: warning
            component: k8sgpt
          annotations:
            summary: "Erreurs d'analyse K8sGPT"
            description: "Le taux d'erreur d'analyse est de {{ $value }} erreurs/seconde"
