#!/bin/bash
# Quick Reference - K8sGPT Monitoring Sans Registry

echo "======================================"
echo "📋 K8sGPT Monitoring - Quick Reference"
echo "======================================"
echo ""

# Verify setup
echo "🔍 Vérification setup actuelle:"
echo ""

echo "✓ Fichiers créés:"
echo "  - QUICKSTART.md (démarrage en 3 commandes)"
echo "  - GETTING-STARTED.md (guide complet)"
echo "  - README-LOCAL-DEPLOYMENT.md (troubleshooting)"
echo "  - PROMETHEUS-CONFIG.md (configuration Prometheus)"
echo "  - 00-START-HERE.md (ce fichier)"
echo ""

echo "✓ Docker & Kubernetes:"
echo "  - Dockerfile (image Docker)"
echo "  - k8sgpt-exporter-deployment.yaml (manifest K8s)"
echo "  - k8sgpt-servicemonitor.yaml (Prometheus)"
echo ""

echo "✓ Scripts déploiement:"
echo "  - deploy-local.ps1 (Windows PowerShell)"
echo "  - deploy-local.sh (Linux/Mac/WSL)"
echo "  - build-local.sh (build uniquement)"
echo ""

echo "======================================"
echo "🚀 DÉMARRAGE RAPIDE"
echo "======================================"
echo ""

echo "1️⃣ Déployer (tout automatique):"
echo ""
echo "   Windows:"
echo "   └─ cd exporter && .\\deploy-local.ps1"
echo ""
echo "   Linux/Mac:"
echo "   └─ cd exporter && chmod +x deploy-local.sh && ./deploy-local.sh"
echo ""

echo "2️⃣ Vérifier les pods:"
echo "   └─ kubectl get pods -n k8sgpt"
echo ""

echo "3️⃣ Accéder aux métriques:"
echo "   └─ kubectl port-forward -n k8sgpt svc/k8sgpt-exporter 8080:8080"
echo "   └─ curl http://localhost:8080/metrics"
echo ""

echo "4️⃣ Configurer Prometheus:"
echo "   └─ Voir PROMETHEUS-CONFIG.md"
echo ""

echo "5️⃣ Importer Dashboard Grafana:"
echo "   └─ Utiliser grafana-dashboard.json"
echo ""

echo "======================================"
echo "✅ VERIFICATION POST-DEPLOIEMENT"
echo "======================================"
echo ""
echo "Pas de pod exporter?"
echo "  → kubectl logs -n k8sgpt -l app=k8sgpt-exporter"
echo ""
echo "Pas de métriques?"
echo "  → Vérifier: kubectl get results -n k8sgpt"
echo "  → (K8sGPT n'a peut-être pas encore tourné)"
echo ""
echo "Prometheus ne scrape pas?"
echo "  → Status → Targets (doit être GREEN)"
echo ""

echo "======================================"
echo "📚 DOCUMENTATION"
echo "======================================"
echo ""
echo "START-HERE         → Ce fichier"
echo "QUICKSTART.md      → 3 commandes pour démarrer"
echo "GETTING-STARTED.md → Guide détaillé + architecture"
echo "README-LOCAL.md    → Troubleshooting complet"
echo "PROMETHEUS-CONFIG  → Configuration détaillée"
echo ""

echo "======================================"
echo "⏱️ TEMPS APPROXIMATIF"
echo "======================================"
echo ""
echo "Build image:        2-3 minutes"
echo "Load dans cluster:  ~30 secondes"
echo "Déployer ressources: ~30 secondes"
echo "──────────────────────────────"
echo "Total:             ~5 minutes ⚡"
echo ""

echo "======================================"
echo "🎯 PROCHAINES ÉTAPES"
echo "======================================"
echo ""
echo "1. Lancer deploy-local.ps1 ou deploy-local.sh"
echo "2. Vérifier kubectl get pods -n k8sgpt"
echo "3. Tester curl localhost:8080/metrics"
echo "4. Configurer Prometheus (voir doc)"
echo "5. Importer dashboard Grafana"
echo "6. Configurer alertes (optionnel)"
echo "7. Teams webhooks (optionnel)"
echo ""

echo "======================================"
echo "✨ VOUS ÊTES PRÊT!"
echo "======================================"
echo ""
